### ISSUE TITLE
scalebar overlaps user panel

### ISSUE THREAD

**Issue by xgui3783** [r03ert0/microdraw#100]
### Is this a feature request or a bug report? 
bug

### What is the current behaviour?
scalebar overlaps user panel
![microdraw_login_scalebar_overlay](https://user-images.githubusercontent.com/19381783/31768252-d7c93062-b4ce-11e7-9e3e-9c0f01c9928a.PNG)
 (see attached screenshot)

* If this is a bug, please explain how to reproduce the problem 
open any image, zoom in so scale bar is at top right most position

### What is the expected or desired behavior?
scale bar resides below the user panel

### Version information (for bug reports)
Chrome 61.0
Windows 10

* Paste the output of these commands:
```
node --version && npm --version
```
`node --version`:v6.10.2
`npm --version`: 3.10.10

**Comment by surmistry** [comment]
Hi @xgui3783 mind if I take a look at this?

**Comment by xgui3783** [comment]
Sure. Hopefully you can come up with a better solution than
https://github.com/r03ert0/microdraw/tree/fix_overlap?files=1

**Comment by xgui3783** [comment]
Apologies for the short remark. Please allow me to clarify. Setting the yOffset results in:
![overlay_true](https://user-images.githubusercontent.com/19381783/31810274-6b8ba832-b57b-11e7-9322-4add15aa859a.PNG)

which is the intended behaviour. However, when user navigate away from the corner:

![overlay_false](https://user-images.githubusercontent.com/19381783/31810281-77a0baea-b57b-11e7-8c1a-5f2cd24a92ff.PNG)
which is ... functional. If there is a way to anchor it to the top right corner of the image, and, upon collision with the user panel, it anchors below the userpanel, that'd be amazing.
