### ISSUE TITLE
test failed in docker-ized microdraw

### ISSUE THREAD

**Issue by xgui3783** [r03ert0/microdraw#103]
### Is this a feature request or a bug report? 
bug

### What is the current behaviour?

* If this is a bug, please explain how to reproduce the problem 
After configuring the package
`npm run test`
produces error and does not finish the tests
error log:
![docker_test](https://user-images.githubusercontent.com/19381783/31776778-b7e6b76a-b4ec-11e7-89e9-40f0abd452c5.PNG)
apologies for screenshot, formatting of the stdout was a bit bizarre. 

### What is the expected or desired behavior?
tests completed without error

### Version information (for bug reports)
Browser: none applicable
OS: Windows 10 + Kitematic
`docker --version` : 17.03.0-ce

* Paste the output of these commands:
```
node --version && npm --version
```
host os:
`node --version`: 6.10.2 `npm --version` : 3.10.10
docker:
`node --version`: 8.7.0 `npm --version` : 5.4.2

**Comment by xgui3783** [comment]
possibly related:
https://github.com/Googlechrome/puppeteer/issues/290

**Comment by r03ert0** [comment]
it looks like a problem getting puppeteer (headless chromium). To get it running in circleci, I followed this instructions:

https://github.com/Quramy/puppeteer-example

**Comment by r03ert0** [comment]
(you can have a look at .circleci/config.yml)

**Comment by pglock** [comment]
Fixed in 3b96d29
there were some missing dependencies for puppeteer. I updated the Dockerfile to install them.
You can also run the tests via `docker -i -t microdraw tests`

**Comment by r03ert0** [comment]
awesome! thanks!
