### ISSUE TITLE
test.js never draws the triangle?

### ISSUE THREAD

**Issue by xgui3783** [r03ert0/microdraw#117]
### Is this a feature request or a bug report? 
* Please choose one of the labels on the right side and tag your issue :)

question

### What is the current behaviour?
Upon inspecting the steps in `test.js`, the logic seems to indicate that it tries to delete the triangle before making the triangle?

* If this is a bug, please explain how to reproduce the problem 
    * Which tools did you use in which sequence?
    * What is the resolution of your data? (Can you provide a link to your data?)
    * Do not include sensitive information.
    * Upload the browser error message if you are familiar with web developer tools.

`test.js`

### Version information (for bug reports)

* **Browser + version**:
* **Your OS and version**:
* Paste the output of these commands:
```
node --version && npm --version
```

**Comment by r03ert0** [comment]
hi @xgui3783 
for me, I do see the triangle, but the part when the triangle is deleted fails, which makes that when I look at the cat slice I have a bunch of triangles drawn one on top of the other...

**Comment by xgui3783** [comment]
hi @r03ert0 , correct me if I have misunderstood, 

https://github.com/r03ert0/microdraw/blob/master/test.js#L46

As soon as cat.png is loaded, test attempts to delete the triangle? I would imagine the logical test would be: load cat.png -> draw triangle -> delete triangle ... (remaining steps)

**Comment by xgui3783** [comment]
Aww, I understand. That makes complete sense =) thanks for the clarification
