### ISSUE TITLE
even anonymous user can shutdown the microdraw node-express server ?

### ISSUE THREAD

**Issue by xgui3783** [r03ert0/microdraw#119]
https://github.com/r03ert0/microdraw/blob/ca15f3d7ed5c94ffbcd1bc486fb2f8e012debd5e/app.js#L286

by sending a post request to http://HOSTNAME/api with a stringified JSON body with a key value pair of "action":"detente"?

**Comment by r03ert0** [comment]
oops... I used that for testing, but need to take it off...

**Comment by r03ert0** [comment]
i removed the "detente" script
