### ISSUE TITLE
autoimport tools rather than manual import

### ISSUE THREAD

**Issue by xgui3783** [r03ert0/microdraw#123]
### Is this a feature request or a bug report? 
* Please choose one of the labels on the right side and tag your issue :)

feature request (ish?) soliciting feedback/interest

### What is the current behaviour?
Developing new tools, developers for now need to manually include the js file, then patch `microdraw.js`, then `data.mustache`. Ideally, tools in `public/js/tools` should be automagically be imported, without needing to patch `microdraw.js` and `data.mustache`

Is there an apeptite for a feature like this?

* If this is a bug, please explain how to reproduce the problem 
    * Which tools did you use in which sequence?
    * What is the resolution of your data? (Can you provide a link to your data?)
    * Do not include sensitive information.
    * Upload the browser error message if you are familiar with web developer tools.

### Version information (for bug reports)

* **Browser + version**:
* **Your OS and version**:
* Paste the output of these commands:
```
node --version && npm --version
```

**Comment by xgui3783** [comment]
I have a working version at https://github.com/r03ert0/microdraw/tree/autoimport_migrated_tools , the current problem is that they are imported in random order (async), and the order of import (currently) determine the order at which they appear on the UI.

**Comment by r03ert0** [comment]
hi @xgui3783 !
we do want to keep some organisation in the tools.
Adding the tools in the right order in `configuration.json` sounds very reasonable. I'd also like the idea of being able to provide different "presets", like a navigation preset, a text annotation preset, a vectorial annotation preset, etc. Probably the presets could go in a `tool-presets` directory, all available presets could be loaded automatically, and the default preset could be selected in `configuration.json`?
