### ISSUE TITLE
magicV breaks older annotations

### ISSUE THREAD

**Issue by xgui3783** [r03ert0/microdraw#135]
## Hi! Thank you for getting back to us! <3

Hi, I would like to highlight that annotations made with older version of microdraw will be offset incorrectly in the newer version as a result of the magicV. In particular, a lot of the annotations we did had:

https://github.com/r03ert0/microdraw/blob/c9987d195b484d9f13a022a3541a932c795bf0c1/microdraw.js#L1204

```
magicV = viewer.world.getItemAt(0).getContentSize().x;
```

but the latest version had:
https://github.com/r03ert0/microdraw/blob/master/app/public/js/microdraw.js#L1464
```
//me.magicV = me.viewer.world.getItemAt(0).getContentSize().x / 100;
```

Needless to say, when we tried to import older annotations in the new microdraw, it didn't turn out initially. 

I don't actually know the solution to this problem. Or if this is intended / a problem at all. 

### Is this a feature request or a bug report? 
* Please choose one of the labels on the right side and tag your issue :)

### What is the current behaviour?

* If this is a bug, please explain how to reproduce the problem 
    * Which tools did you use in which sequence?
    * What is the resolution of your data? (Can you provide a link to your data?)
    * Do not include sensitive information.
    * Upload the browser error message if you are familiar with web developer tools.

### Version information (for bug reports)

* **Browser + version**:
* **Your OS and version**:
* Paste the output of these commands:
```
node --version && npm --version
```

**Comment by hspitzer** [comment]
I don't have a solution, but a comment: I think that the reason why we (at FZJ) were using the magicV without dividing by 100 was that we wanted to have annotations that can be directly overlaid on the image at the original resolution. This is very important when running automatic analysis pipelines on the annotations (e.g. a user segmented a structure, and we want to crop it afterwards). It is certainly no problem to change that, but something to keep in mind. Personally, I think it would be nice if the annotations were directly related to the original image in such a way.

**Comment by xgui3783** [comment]
Apologies, probably implementation details on our end.
