### ISSUE TITLE
error on making 10th or more annotation

### ISSUE THREAD

**Issue by HafezEM** [r03ert0/microdraw#139]
### What is the current behaviour?

* It gives an error when try to create 10 or more annotations. I tired the bigbrain, vervet, ferret and more files  and the following error appears on placing the 10th annotation (by DrawPolygon or Drawline). 

On the browser/Developer tools/Console:
Uncaught TypeError: Cannot read property 'classList' of null

I believe the error comes from:
tag.classList.remove("deselected") when the 10th annotation is made.

### Version information (for bug reports)

* **Browser + version**:
Version 58.0.3029.110 (64-bit)
* **Your OS and version**:
Ubuntu 16.04

**Comment by xgui3783** [comment]
Hi @HafezEM ,
Hmm, that's strange, I believe 6263d1d01fba8a789a4c7b145ad2bfef27b7624d was meant to fix the issue you described. 

a quick test just now with the latest  master branch, I could add more than 10 annotations:

![screenshot from 2018-07-07 23-12-38](https://user-images.githubusercontent.com/19381783/42414725-bc270b64-823b-11e8-8794-e8e9916855dc.png)

Are you able to check the latest commit of the microdraw you are running? alternatively, can you check if https://github.com/r03ert0/microdraw/blob/master/app/public/js/microdraw.js#L235 has been modified in the version you are using?

Kind regards,
Xiao

**Comment by HafezEM** [comment]
Thank you so much Xiao. I had cloned https://github.com/neuroanatomy/microdraw because I couldn't follow some installation instructions of  https://github.com/r03ert0/microdraw. 

In Developer install instructions -> Basic Steps -> some instructions like github-keys.json.example -> github-keys.json, public/js/configuration.json.example -> public/js/configuration.json and server_config.json.example -> server_config.json match neuroanatomy/microdraw and not /r03ert0/microdraw. 

Should I use https://github.com/r03ert0/microdraw  or https://github.com/neuroanatomy/microdraw is good enough?

Regards,
Hafez

**Comment by xgui3783** [comment]
with 812472d20bd14e3740aa9227630ebe2066ac6bd7 the readme should be updated and `docker-compose.yml` included

**Comment by HafezEM** [comment]
Hi @xgui3783,

Thank you so much for your reply. That worked. The only thing I had to change was to create symbolic link for openseadragon, openseadragon-screenshot and FileSaver.js in /app/public/lib folder. You might need to take that into consideration.

Regards,
Hafez

**Comment by xgui3783** [comment]
closed via a8646235f4010d85c85d20397fc82a8462592a0a
