### ISSUE TITLE
Translate is broken.

### ISSUE THREAD

**Issue by natacha-beck** [r03ert0/microdraw#14]
I think this line is the guilty one.

https://github.com/r03ert0/microdraw/blob/master/microdraw.js#L495

**Comment by natacha-beck** [comment]
Works on Chrome and break on Firefox

**Comment by r03ert0** [comment]
Firefox was sensitive to a bug in line 555 of microdraw.js, mouseDarg function, "select" switch case. I commented it out and 'translate' now works in Firefox. Commit 51c21bd
