### ISSUE TITLE
Shift in annotations cause by me.transform()

### ISSUE THREAD

**Issue by HafezEM** [r03ert0/microdraw#154]
Hi,

I am trying to load annotations from file on the MicroDraw but I am have a difficult time because they are placed not on the correct spots. I found out this shift is because of me.transform() that is called at the end of initAnnotationOverlay() function. If I comment out me.transform() line, the with one click on the image or zoom, annotations get shifted because me.transform() is called. If you comment out me.transform() at the end of initAnnotationOverlay() function, even when you draw an annotation, it gets shifted when you zoom. I was wondering why this shift happens for the first time me.transform() is called and how can I solve this issue. 

Kind Regards,
Hafez

**Comment by xgui3783** [comment]
Hi @HafezEM 

are your annotations in the same space as our image? We ran into a similar issue, and we solved it by replacing this line:
https://github.com/r03ert0/microdraw/blob/master/app/public/js/microdraw.js#L1460

with the following line:
```
me.magicV = me.viewer.world.getItemAt(0).getContentSize().x;
```

relevant issue:
https://github.com/r03ert0/microdraw/issues/135

**Comment by HafezEM** [comment]
Hi @xgui3783 
Thank you for your reply. My annotations in the space of image pixels but I convert them to your space by the following:

pixelConversion: function pixelConversion(pixel) {
        var convertedPixel = {};
        //console.log("HHHHHH " + pixel.length)
        for(i=0; i<pixel.length; i++) {
	    dot = pixel[i];
            var inversion1 = me.viewer.viewport.imageToViewportCoordinates(dot.point.x, dot.point.y);
	    var inversion2 = me.viewer.viewport.pixelFromPoint(inversion1, true);
            convertedPixel[i] = inversion2;
            }
            return convertedPixel;
        },

I tried to use me.magicV = me.viewer.world.getItemAt(0).getContentSize().x;
and me.magicV = me.viewer.world.getItemAt(0).getContentSize().x/100; both but neither fixed the issue.

I appreciate if you could give me a solution to this.

Thank you so much,
Hafez

**Comment by HafezEM** [comment]
Hi @xgui3783,

Actually your solution worked. I removed my conversion function and now the annotations lie on the correct spots. Thank you so much.

Regards,
Hafez

**Comment by xgui3783** [comment]
glad I could help
