### ISSUE TITLE
color menu does not close

### ISSUE THREAD

**Issue by katjaq** [r03ert0/microdraw#162]
color value goes to NaN
rectangle does not close

**Comment by xgui3783** [comment]
rectangle as in the popup window? I think when one clicks OK, it does close?

**Comment by katjaq** [comment]
Thank you for looking into this. 
yes, it should :) 
For me, it does not. I had to click the color field again to close it. The complete color menu did not work as it did not connect to "reg", so alpha defaulted to NaN and no color could be changed nor stroke width. 
I will pull your push and try now :)

many thanks for your help!

**Comment by xgui3783** [comment]
out of curiosity, which browser + version are you using? 

In chrome, colour picker show a dialog, which can only be dismissed by clicking x. Then, one must click the `ok` button. 

Is there a more desirable way of interacting with the colour widget?
