### ISSUE TITLE
Problem link to the json file through the url

### ISSUE THREAD

**Issue by celinede** [r03ert0/microdraw#172]
hello,
When I have a look at the json of a given contour, the link doesn't seem to point to the right place ...

I first draw and save a contour.
Then update the url to reach the json I get data from different subjects and sections. cf Pictures

![Screenshot from 2019-03-29 14-09-59](https://user-images.githubusercontent.com/18595712/55321257-7f001a80-5479-11e9-935d-04658f41b3ab.png)
![Screenshot from 2019-03-29 14-07-24](https://user-images.githubusercontent.com/18595712/55321258-7f001a80-5479-11e9-8aaa-7ce903f7333e.png)

**Comment by xgui3783** [comment]
hi @celinede , can you print what you see when you replace the `&` with `%26`? ie, what do you get when you: `http://microdraw.pasteur.fr/api?source=/F107_P4/F107_P4.json%26slice=74` ?

**Comment by celinede** [comment]
Hi !
I get the same as previously...
![Screenshot from 2019-04-01 14-30-20](https://user-images.githubusercontent.com/18595712/55327613-c2af5000-548a-11e9-8938-4b23c2051ea1.png)

**Comment by xgui3783** [comment]
I think I might have pin pointed the issue:
https://github.com/r03ert0/microdraw/blob/master/app/routes/routes.js#L46
I believe GET requests understand fileID and slice as two separate query params. 

I am devising a fix ATM

**Comment by xgui3783** [comment]
oh, wait, I think I have been looking at the wrong places. can you check:
`http://microdraw.pasteur.fr/api?fileID=/F107_P4/F107_P4.json&slice=74`
?

**Comment by celinede** [comment]
It's empty...

**Comment by xgui3783** [comment]
hmm, how about `http://microdraw.pasteur.fr/api?fileID=/F107_P4/F107_P4.json%26slice=74`
?

**Comment by celinede** [comment]
yes it works !

**Comment by xgui3783** [comment]
Hmm, I think two things will need to be fixed. 

1/ would be ideal if we could change fileID -> source (at least in the query parameters)
2/ the `updateAnnotation` / `findAnnotations` is a bit wonky, and does not currently have slice implemented. 

I am working on a fix that should fix both issues.

**Comment by celinede** [comment]
thank you ! 
let me know if the url format changes
