### ISSUE TITLE
Download json for a contour drawn from a private account 

### ISSUE THREAD

**Issue by celinede** [r03ert0/microdraw#175]
Hi,
I used to be able to download my contours from Python, however since the last updates I can only access contours that have been drawn while logged out.
How can I access the contours that I've drawn while logged in with my Github account ?

**Comment by xgui3783** [comment]
Hmm... I remember @r03ert0 briefly spoke about a token, which could authenticate the user, but I can't remember very clearly. 

How are the contours retrieved before from python? 

I can probably reimplement that.

**Comment by celinede** [comment]
yes, I guess that the token would be the right solution...

 in python I was doing as follow:
> from urllib.request import urlopen
> import json
> url = 'http://microdraw.pasteur.fr/api?fileID=/'+subject+'/'+subject+'.json%26slice='+str(slicenb)
> response = urlopen(url)
> data = json.loads(response.read().decode())

**Comment by r03ert0** [comment]
done with PR #177
