### ISSUE TITLE
Different json encryption for selected and not selected polygons

### ISSUE THREAD

**Issue by celinede** [r03ert0/microdraw#178]
Hello,

This is not a big issue but a small inconvenience.

I have noticed that at least for polygons, when they are selected or not their encryption in the json file changes pretty much, which is inconvenient for automatic data extraction afterwards. Instead of having a simple switch that goes on and off, the point coordinates switch from [xvalue,yvalue] (when not selected) to {"x":xvalue,"y":yvalue,"selected":true} (when selected).
 
If possible it would be nice to have a consistent format for selected and not selected contours.

![Screenshot from 2019-04-08 16-04-37](https://user-images.githubusercontent.com/18595712/55730444-7fb82400-5a18-11e9-919d-677fdfa26d20.png)

**Comment by xgui3783** [comment]
hmm, I believe this is a quirk of paperjs. I believe I have dealt with this exact issue, and the solution at the time was to deselect all regions when saving. 

Unless there are some clear objections, I will see if I can reimplement that.

**Comment by celinede** [comment]
Hi,
I still have the same issue...
here is an example:
http://microdraw.pasteur.fr/api?source=/F107_P4/F107_P4.json&slice=56

**Comment by xgui3783** [comment]
Hmm, I can reproduce this issue:

1/ navigate to a project with multiple images
2/ annotate in image 1, leave a region selected
3/ move to image2
4/ click save

One fix might be, when user navigate away from an image, deselect all the current annotation.
Would that be fitting to the usecase?

**Comment by celinede** [comment]
yes, in my case I don't need a given annotation to stay selected after I've moved to another section.
In the save action it should also deselect all the annotations for the current section.

**Comment by celinede** [comment]
One more info about this issue, I have noticed that a region is automatically selected when we open a new slice. Which in the end, even if you don't do any modification to the slice and move on to the next ones, the slice will be saved again with the modification of the format as selected region.
