### ISSUE TITLE
Server constantly checking for access token

### ISSUE THREAD

**Issue by r03ert0** [r03ert0/microdraw#181]
the server is constantly checking for access token, even when only viewing a slice, which slows it down. We get long threads of:

```
>> Check token
>> No token
>> Check token
>> No token
>> Check token
>> No token
>> Check token
>> No token
...
```

**Comment by xgui3783** [comment]
hmm, I guess that's the disadvantage of baking the token checking into a middleware. 

Lemme see if that can solved

**Comment by r03ert0** [comment]
changed `require('./auth/token')(app);` by `require('./auth/token');`
