### ISSUE TITLE
Ability to programmatically upload contours

### ISSUE THREAD

**Issue by r03ert0** [r03ert0/microdraw#186]
I'm currently working on this, and would like to discuss some issues.

Contours could be uploaded using `curl`, using:

```
curl -X POST -F 'data=@/path/to/file.json' 'http://microdraw.pasteur.fr/api/upload?action=save&source=[url of brain].json&slice=0&token=[a valid token]'
```

I would like to stop storing and using hashes server side. Currently, the microdraw client computes a hash based on all the annotations in a slice to determine whether to save or not. The hash for the complete slice is sent to the server upon saving, however, annotations (regions, contours) are saved individually. Each annotation is currently inheriting the slice hash, which makes that they all have the same hash! Maybe at some point it'll be a good idea to compute per-annotation hashes, but right now I think the best would be to keep the server unaware of hashes, and use hashes only on the client as a method to decide whether to save or not.

**Comment by xgui3783** [comment]
hmm makes sense. 

so on annotation load, client calculates hash. on subsequent saves, client calculates hashes. If the hash is different, it sends to the server to be saved. 

I think it should be implemented in `microdraw.js` and not in `save.js`. 
Perhaps with a new method, something like `getUnsavedAnnotations()` which returns (or resolves) all annotations with hashes different to the previous save. 

This could also solve a widely requested feature in our institute: showing which annotation are modified, and show warning if user is about to navigate away.

**Comment by r03ert0** [comment]
the `getUnsavedAnnotations` idea is good!
I merged a PR for the programmatic upload. I haven't removed the `hash` stuff yet.

**Comment by r03ert0** [comment]
(i'll close the issue, because of PR #187 , but we can keep the discussion here)

**Comment by xgui3783** [comment]
commit looks solid. 

Curious as if `req.body.action` is still needed? we could simplify the code a lot.

**Comment by r03ert0** [comment]
it's true. It's kind of redundant with upload

**Comment by r03ert0** [comment]
@xgui3783 ? How and where would you add tests for the functions inside `/api/index.js`?
I have, for example, this one:
```
    it('should detect a proper annotation object as such', (done) => {
        const ann = [{annotation:{path:[
            "Path",
            {applyMatrix:true,segments:[[10,10],[20,20]],closed:true,fillColor:[1,0,0,1],strokeColor:[0,0,0],strokeScaling:false}
        ],"name": "Test"}}];
        assert(validateAnnotation(ann)).to.be.true;
        done();
    });
```

**Comment by xgui3783** [comment]
testing `saveFromAPI` ?

Hmm my approach would be changing 

```
const saveFromAPI = function () {}
```

to 
```
const saveFromAPI = function () {}
exports.saveFromAPI = saveFromAPI
```

then one can import the function like this:

```
const { saveFromAPI } = require('./api/index.js')
```

**Comment by r03ert0** [comment]
This is another example
[test.json.zip](https://github.com/r03ert0/microdraw/files/3106951/test.json.zip)
