### ISSUE TITLE
Running the mocha tests erases the complete MongoDB

### ISSUE THREAD

**Issue by r03ert0** [r03ert0/microdraw#220]
Bug report

### What is the current behaviour?
Running `npm run mocha` erases the complete MongoDB, leaving only the test entries inserted by the test.

### What is the expected or desired behavior?
Tests should be ran in a temporary DB

### Version information (for bug reports)
```
$ mongo --version
MongoDB shell version v3.4.10
git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
    distmod: rhel62
    distarch: x86_64
    target_arch: x86_64
```

**Comment by xgui3783** [comment]
Hmm, yes, that's totally the current behaviour 😰😰, I hope it hasn't caused any damages. I will see to make a patch for this.

**Comment by r03ert0** [comment]
if i remember well, at some point the tests were using a different database called microdraw_mocha_test (it still shows up). Maybe that DB could be used for test and deleted every time?
