### ISSUE TITLE
Microdraw tool as a library 

### ISSUE THREAD

**Issue by Kartheekgolla1** [r03ert0/microdraw#246]
we have case that microdraw is a tool(web application) is an open source application that works with URL which is given in iframe tag, we dont need this instead what we need is whether we can include microdraw as a Library . so will it work ? Like we have to open this application directly from Angular if we give that as an library.

Do you have some tips to help us with that ?

Your help would be greatly appreciated.

**Comment by r03ert0** [comment]
we have never considered that possibility, and haven't done anything to make microdraw work as a library. My hunch is that it won't be possible... but curious to know if you manage to do it!

**Comment by r03ert0** [comment]
keep also in mind that microdraw has a GPL 3 license, which is a viral license, so your tool will inherit microdraw's permissions.
