### ISSUE TITLE
Login dialog disappears together with the toolbar

### ISSUE THREAD

**Issue by hspitzer** [r03ert0/microdraw#30]
When trying to log in using the login link at the upper left corner, the dialog for entering username and password disappears once the focus of the mouse is removed from the toolbar. 
This makes logging in a bit difficult :-)

Additionally the keyboard shortcuts should probably be disabled when typing in an textfield

**Comment by r03ert0** [comment]
changing the automatically hiding toolbar by a menu button + close button should fix this issue (@katjaq is working in it)

**Comment by katjaq** [comment]
hahaaa, sorry for hiding the login window altogether with the toolbar -- implemented hide menu on button click now ;)
however, the question if keyboard shortcuts should be disabled during login remains

**Comment by r03ert0** [comment]
The navigator was not hidden by the new close button, and it covered a large part of the screen in iphones (and other devices with small screens I imagine). I included now the navigator in the menuBar.
