### ISSUE TITLE
draw-polygon unexpected behavior & breaks other utils:

### ISSUE THREAD

**Issue by katjaq** [r03ert0/microdraw#36]
1) when a region is selected, draw-polygon concatenates the new-to-be-drawn one to the selected one (at closing point)
2) when no region selected, it doesn't draw anything but breaks the tool (no util would work after that)

this is the version on siphonophore now; tested in chrome, firefox & safari

**Comment by katjaq** [comment]
works in the new version

**Comment by r03ert0** [comment]
(time to update siphonophore...)
