### ISSUE TITLE
in the macaque example some .jpg files cannot be found & loaded by openseadragon

### ISSUE THREAD

**Issue by katjaq** [r03ert0/microdraw#41]
i get this error on siphonophore as well as locally
which causes that in default zoom some slices lack their upper corners; once zoomed in (and then out again), the slices look all fine

**Comment by r03ert0** [comment]
should be fixed now. Could you try it and close the issue if it works?

The sizes of the slices are described in the macaque.jsonp file at cnrs.fr.
For the test I had used the same slice size for all slices, which was
incorrect. Now I corrected the sizes (manually for the moment, but I'm
trying to write a script to generate a source description automatically).

**Comment by katjaq** [comment]
yes, it works all fine :) great!!!
