### ISSUE TITLE
When dividing a region, the new region keeps the old colour instead a new one based on its name

### ISSUE THREAD

**Issue by r03ert0** [r03ert0/microdraw#43]
When dividing a region, the new region keeps the old colour instead a new one based on its name.

1. draw region A
2. draw region B overlapping A, region B is selected.
3. select the divide tool and click on A
4. region A is now divided in 2 parts.

Expected result: The new part (the one in common with B) is named 'Untitled 1' and has a colour based on the name ('Untitled 1' in this case). The region appears in the region list with the new colour

Observed result: The new region has the same colour as A, different from the color in the region list, which seems to be correctly computed based on the name

**Comment by katjaq** [comment]
done in #6ca83e7
