### ISSUE TITLE
Color changing menue does not disappear when selecting another region

### ISSUE THREAD

**Issue by hspitzer** [r03ert0/microdraw#47]
The color changing menu (color picker) behaves not as expected when switching regions:
- selecting menu of region a (click on colored rectangle) when menu of region b is already activated results in the menu disappearing 
- selecting region a (click on name of region) when menu of region b is activated results in the menu still shown but the information of region b still selected.

I would expect the following behaviour:
- selecting menu of region a (click on colored rectangle) when menu of region b is already activated results in the menu showing the information of region a now
- selecting region a (click on name of region) when menu of region b is activated results in the menu disappearing (or alternatively the menu showing the information of region a)

**Comment by katjaq** [comment]
fixed :)
now, click on color tag of region a opens colorPicker, click on color tag of region b will show updated colorPicker; click on name of region b as well; click on drawn region b as well
when clicking the color tag or the name of the selected (same) region, the colorPicker will disappear

**Comment by hspitzer** [comment]
Great! I love it!
