### ISSUE TITLE
How to re-draw the curved regions using the saved region coordinates?

### ISSUE THREAD

**Issue by zizhaozhang** [r03ert0/microdraw#51]
Hi
The drawn regions are saved as several point coordinate. May ask how to redraw them using the saved region coordinates? What kind of interpolation functions to control the outlining curves?

**Comment by r03ert0** [comment]
curves are saved vectorially, as cubic Beziers. For any pair of points
('anchors') there are 2 control points that determine the shape of the
curve joining them. If the control points are the same as the anchors, the
line is straight.
