### ISSUE TITLE
save annotations separately based on region name and not just the entire slice

### ISSUE THREAD

**Issue by katjaq** [r03ert0/microdraw#64]
Current behaviour:
MicroDraw saves annotations slicewise. It stores in pixel coordinates 
the curves (as numbers), the slice number, the region name, the user name
Saving as a json file seems great to being able to query inside!

Suggested behaviour:
This is an idea to enhance the saving to the database: save regions one by one to separate database entries based on their names. This will enable easy getting of one structure to aim at a 3D reconstruction.

**Comment by pglock** [comment]
Hi
What should a database entry for a  region look like?

Currently:

- **source**: file identifier
- **user**: UserID, who made the annotation
- **section**: section identifier
- **annotationHash**: needed for undo
- **annotation**: the region path and the name
- **backup**: Flag, replaces timestamp?

I'd like to propose some new attributes:

- **type**: the type of the annotation, e.g. "cells", "cortigal_region" or "artifact"
- **visibility**: private/public, if public everyone can load the annotation

### /api get request

At the moment **source** and **section** are queried. If **source** is the fileID, querying **source** and **user** should be sufficient. The request should return an array of all queried annotations.

### /api post request

The post request should be able to save a list of annotations ( all annotations of the current section) to the database.

### client changes


* provide type value
* provide visibility value, can default to private
* expect a list of annotations from get
* provide a list of annotations for post

Looking forward to your remarks ;)
