### ISSUE TITLE
removing the requirement of the CORS header of source JSON

### ISSUE THREAD

**Issue by xgui3783** [r03ert0/microdraw#71]
### Is this a feature request or a bug report? 
Feature request

### What is the current behavior?
During development and production, the json pointed by source parameter requires a CORS header, or be in the same domain. Otherwise a missing CORS header error will be thrown. 

### What is the expected or desired behavior?
Any JSON can be used, CORS header or not.

### Version information (for bug reports)
will provide at a later date

### Other
I will be happy to provide a fix and PR on this issue. Not a pressing concern, but minor annoyance.

**Comment by katjaq** [comment]
WOW!! That would be fantastic if you knew how to solve this issue!! \ö/ Please go ahead. 

I assigned it to you and added the Hacktoberfest label! <3 Thank you very much for your interest and you contribution!! 👍

**Comment by r03ert0** [comment]
hi @xgui3783 !
how do you do not to required the CORS header? I thought that's something you had to setup in your server...

**Comment by xgui3783** [comment]
I was going via that route. Since node express already serve the static
files, it could fetch the json first and pass the fetched json to the
rendered obj
