### ISSUE TITLE
symlink openseadragon not recognised in windows

### ISSUE THREAD

**Issue by xgui3783** [r03ert0/microdraw#72]
### Is this a feature request or a bug report? 
Bug, Enhancement

### What is the current behavior?
When developing on a Windows machine, it does not properly recognise symlinks, leading to error on page load. Manually rename the openseadragon lib folder would fix the issue, but a minor annoyance.

### What is the expected or desired behavior?
Windows developing machine can find the library without manual renaming.

### Version information (for bug reports)
Windows10

### Other
I will be happy to look into a fix and provide a PR

**Comment by katjaq** [comment]
Yes pleaaaaase! 😃  That would be amazing if you could provide a fix for this issue!! We do not have any windows machines for testing here... Thank you very very much! 

I assigned the issue to you, and I added the label Hacktoberfest. <3

happy hacking!

**Comment by r03ert0** [comment]
hi @xgui3783 !
I'm using the symlinks to update more easily to new library versions, by including the symlink name instead of the real library name. How would you do that in Windows?

**Comment by xgui3783** [comment]
Hmm haven't considered yet. Node should have a library that detects OS

**Comment by pglock** [comment]
While this does not solve the issue directly, PR #95 provides docker support. If you have docker installed, you can at least start microdraw in a container.

**Comment by xgui3783** [comment]
just tested dockerized microdraw on windows. it seems existing on windows fs permanently destroys the symlink. `ls -l openseadragon` returns:

docker container running in windows:
`-rwxr-xr-x 1 root root 23 Oct 19 11:44 openseadragon`

docker container running in ubuntu:
`lrwxrwxrwx 1 root root 23 Oct 23 08:40 openseadragon -> openseadragon-bin-2.3.1`

**Comment by xgui3783** [comment]
@r03ert0 @katjaq , @pglock and I were looking into a fix for windows machine unable to parse symlinks. PR #106 provides temporary fix to this, but we are hoping to convince you to use hard links (e.g. `<script src = 'lib/openseadragon-bin-2.4.3'></script>`) 

The obvious winner is developers on windows, who do not need to rename/work with the docker workaround.
Another advantage is that docker-compose script (PR #106) will no longer need to be updated should the symlinks be changed.
Lastly, it is that it is consistent with the rest of the libraries. (see `jquery-1.11.0.min.js` and `paper-full-0.9.25.min.js`)

I understand this creates more work for those who develop in linux and macOS, when one wishes to change the version of OSD, OSD-Screenshot, FileSaver, but I am hoping that this does not happen frequent enough, and the pro outweighs the con. 

Please let us know your opinions.
