### ISSUE TITLE
fix and improve test functionality

### ISSUE THREAD

**Issue by katjaq** [r03ert0/microdraw#87]
### What is the current behaviour?

In last few days, @r03ert0 implemented some first test frameworks, e.g. to test the interface —> ```test-draw.js``` will take some screenshots: 
* picture of the homepage, 
* then it opens a data file,  
* loads the saved annotation (one triangle), 
* then it draws a rectangle, 
* draws a second rectangle, 
* unifies them, 
* deletes them, 
* saves (the triangle will not be deleted) 
and the script takes a screenshot at each step. 

These reference images are stored in ```/test/reference```
Once contributors made their code changes, they can run the script ```node test-draw.js``` and check if the images it generates into ```/test``` are the same as those in the ```/test/reference``` directory.

However, this is a first start to test some tools upon button click. **We would love to have** 
* more tests like the above described addRegion test 
* with the latest changes and updates, we need to check the coordinates for the click still click the correct tool button (I might mess up again when adding the undo... i will delete this comment here as soon as this is done :) 
* add new tests like query the value of some object, and then after the changes query that it s still correct...

Any ideas and contributions are very welcome!! 😃

**Comment by chrisdeely** [comment]
Puppeteer has a class called ```ElementHandle``` which allows you to get a pointer to a DOM element and execute methods against it (such as ```click()```). A more scalable approach to clicking UI elements would be to reference them by element ID rather than pixel coordinates.

I'll put together a PR to illustrate
