### ISSUE TITLE
draw line functionality

### ISSUE THREAD

**Issue by katjaq** [r03ert0/microdraw#88]
### What is the current behaviour?
Currently, MicroDraw allows you to draw a region path as a bezier curve or as a polygon path.

### What is the expected or desired behaviour?
However, experts are often used to drawing cytoarchitechtonic borders instead of complete regions. (Thanks for bringing this up @hspitzer !!)

So it would be awesome to add the possibility to just draw a line. Currently, drawPolygon requires to close the path. Any escape option would be fantastic. Maybe upon return key or escape key?

**Comment by unixzii** [comment]
I'll do it.

**Comment by katjaq** [comment]
Thank you so much!! \\ö// PullRequest merged <3 Everything working!
