### ISSUE TITLE
Start using https://mochajs.org/ for testing

### ISSUE THREAD

**Issue by r03ert0** [r03ert0/microdraw#92]
### Is this a feature request or a bug report? 
Feature request

### What is the current behaviour?
Puppeteer is installed for testing the user interface, but there's no real testing framework for automating the UI tests and the rest of the code.

### What is the expected or desired behavior?
Start using mocha (https://mochajs.org/) for testing, and include 1 or 2 examples showing how further tests can be implemented.

**Comment by ramyaa** [comment]
I will take this up.

**Comment by ramyaa** [comment]
Working on it.
