### ISSUE TITLE
program hard fails when any of the following files are missing: server_config.json, github-keys.json, configuration.json, base.js

### ISSUE THREAD

**Issue by xgui3783** [r03ert0/microdraw#99]
### Is this a feature request or a bug report? 
* Please choose one of the labels on the right side and tag your issue :)

### What is the current behaviour?
New developer `git clone REPO`, `npm i`, `npm run start`, and is greeted with error message

### What is the expected or desired behavior?
Throw a warning rather than an error. Also show the warning in UI in `/` and/or `/data`.

### Version information (for bug reports)
Chrome 61.0.3163.100
Windows 10
```
node --version && npm --version
```
node --version: v6.10.2
npm --version; 3.10.10

`npm run start` log:
`
> microdraw@0.0.1 start C:\git projects\microdraw20\m2\microdraw
> node ./bin/www
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flag
                 ^
Error: ENOENT: no such file or directory, open 'C:\git projects\micr
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (C:\git projects\microdraw20\m2\microdraw\
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Fil
" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! microdraw@0.0.1 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the microdraw@0.0.1 start script 'node ./bin/www'
npm ERR! Make sure you have the latest version of node.js and npm in
npm ERR! If you do, this is most likely a problem with the microdraw
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this pr
npm ERR!     npm bugs microdraw
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls microdraw
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\git projects\microdraw20\m2\microdraw\npm-debug.log
`

**Comment by r03ert0** [comment]
pull request #102 solves the issue

**Comment by r03ert0** [comment]
sorry, it doesn't : p

**Comment by xgui3783** [comment]
it partially solves the issue :)

**Comment by xgui3783** [comment]
`configuration.js` and `base.js` are now generated via circleci (see #102 )

missing `server_config.json` and `github-keys.json` still crashes `npm run start`

**Comment by xgui3783** [comment]
the files are only generated during tests

**Comment by xgui3783** [comment]
program still hardfails when server_config.json, configuration.json, base.js are missing

**Comment by r03ert0** [comment]
When `server_config.json` is not present, the server displays a warning and then exits with error code =1. Isn't it ok to exit with an error given that the server cannot work without those files? If we don't want to have an error message, then we can replace `process.exit(1)` with `process.exit()`, and the server will just stop, without error message.

**Comment by xgui3783** [comment]
My concern is that, while long term contributors of microdraw will have a
working `server_config.json`, `configuration.json` etc files in the dev
directory, making it a requirement for development or potential users who
wants to have a test run involve a lot of effort, namely:

```
git clone
cd microdraw
npm i
cp server_config.json.example server_config.json
...
npm start
```

to reduce the friction to get a server running, I would love to see
potential developers and users are able to do spin up a microdraw server by:

```
git clone
cd microdraw
npm i
npm start
```

maybe we could have a `production` flag as a environmental variable, if set
to true, the files are required, and if not, it uses a set of default
values (or uses the .example file)?

**Comment by r03ert0** [comment]
oh i see.
indeed, it would be nice to have an easy to install version. We would then make the github keys optional (then, no login), no whitelist/blacklist (set them to "{}"), and maybe not even the mongodb?
